### PR TITLE
updated metric endpoints

### PR DESCRIPTION
**Pull request by de-johannes**

### CODE REVIEW

**Comment by de-johannes** [comment]
Just for the record: When I build this with goreleaser and aftwards with the dockerconfig from this repo, the config runs just fine in my environment. Don't know why the test is failing.

**Comment by de-johannes** [comment]
Just for the record: when I build this with goreleaser and afterwards with the dockerfile from this repo it just runs fine.

**Comment by xshadow** [comment]
That can be, but you haven't adjusted the tests in main_test.go according to your changes.

**Review by 0x46616c6b — CHANGES_REQUESTED** [review]
Thanks for your contribution. We would like to have these changes in the Exporter and would also upload the Dashboard to Grafana. 

Can you split this PR, to first sort the metrics alphabetically and in the second step add the metrics and dashboard. This would be simplify the review process. If you would I can sort the metics and afterwards you can rebase your PR. WDYT?

**Comment by 0x46616c6b** [comment]
Do you still want to bring these changes to the exporter? It would be great if you can split the PRs and we can bring this to the main branch.

**Pull request closed without merging**
