### PR TITLE
Add OCTO metrics

### PR DESCRIPTION
**Pull request by reixd**
Add missing jvb OCTO metrics

### CODE REVIEW

**Comment by murme1** [comment]
very nice, was just about to do the same PR :)

**Comment by reixd** [comment]
¯\_(ツ)_/¯

New endpoints are on the way. Will be a second PR on top of this one

**Comment by 0x46616c6b** [comment]
Thanks for the PR! As @murme1 mentioned it would be great to have the adjustment in the `main_test.go`. I will look why the tests not run in PRs from forked repositories.

**Comment by 0x46616c6b** [comment]
Can you please add the metrics to the test case? Would like to merge this and release a new version. Thanks!

**Comment by reixd** [comment]
WILCO, had a lot to do lately ;)

**Comment by reixd** [comment]
@0x46616c6b done

**Comment by 0x46616c6b** [comment]
Thanks a lot!

**Pull request merged**
