### PR TITLE
add most documented metrics

### PR DESCRIPTION
**Pull request by guelfey**

### CODE REVIEW

**Comment by 0x46616c6b** [comment]
Thanks for this PR. Can you explain, how you receive this stats? We run the Jitsi Videobridge with no special configuration regarding the stats and we receive a JSON like this:

```json
{
   "largest_conference":10,
   "total_sip_call_failures":0,
   "total_participants":1337,
   "conference_sizes":[
      0,
      1,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
   ],
   "bridge_selector":{
      "total_least_loaded_in_region":0,
      "total_split_due_to_load":0,
      "total_not_loaded_in_region_in_conference":0,
      "total_least_loaded_in_region_in_conference":0,
      "total_not_loaded_in_region":0,
      "total_split_due_to_region":0,
      "bridge_count":0,
      "operational_bridge_count":0,
      "total_least_loaded_in_conference":0,
      "total_least_loaded":562
   },
   "total_conferences_created":1337,
   "total_recording_failures":0,
   "conferences":0,
   "total_live_streaming_failures":0,
   "participants":0
}
```

**Comment by 0x46616c6b** [comment]
I found out that there is a difference between `/stats` and `/colibri/stats` endpoint. Your change will use that endpoint right? Whats if we guess the right struct from the endpoint we want to fetch? By default the rest api is disabled so you will not receive any stats from `/colibri/stats`.

**Comment by guelfey** [comment]
Yes, this is only for the metrics from `/colibri/stats` documented in https://github.com/jitsi/jitsi-videobridge/blob/master/doc/statistics.md. I actually can't find any documentation for the `/stats` endpoint, maybe this is from an older version? The definitions seem to be backwards-compatible, anyway - any metric that isn't returned by the endpoint will then just show up with the default value of 0.

**Comment by 0x46616c6b** [comment]
Yesterday I added a basic test for scraping and converting the JSON to the metrics export. Can you rebase the branch and add another test for the documented statistics? Also a hint in the readme (two availiable possible `videobridge-url`) would be nice.

**Pull request merged**
